# Generated by Django 4.0.6 on 2022-08-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_Diet', models.ManyToManyField(to='exercise.exercise')),
                ('food_Diet', models.ManyToManyField(to='food.food')),
            ],
        ),
    ]
