# Generated by Django 4.0.6 on 2022-08-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('Diet', '0001_initial'),
        ('food', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_admin',
            name='exercise_Diet_admin',
            field=models.ManyToManyField(to='exercise.exercise_diet_admin'),
        ),
        migrations.AddField(
            model_name='diet_admin',
            name='food_Diet_admin',
            field=models.ManyToManyField(to='food.food_diet_admin'),
        ),
        migrations.AddField(
            model_name='diet_admin',
            name='user_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='diet',
            name='exercise_Diet',
            field=models.ManyToManyField(to='exercise.exercise_diet_user'),
        ),
        migrations.AddField(
            model_name='diet',
            name='food_Diet',
            field=models.ManyToManyField(to='food.food_diet_user'),
        ),
        migrations.AddField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='customer.customer'),
        ),
    ]
