# Generated by Django 4.0.6 on 2022-08-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exercise', models.CharField(max_length=20)),
                ('calories', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='exercise_diet_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_exercise_customer', models.IntegerField()),
                ('customer_exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('exersise_field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='exercise_diet_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_exercise_admin', models.IntegerField()),
                ('admin_exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('exersise_field_admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise.exercise')),
            ],
        ),
    ]
