# Generated by Django 4.0.6 on 2022-08-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('calories', models.IntegerField()),
                ('mesure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='food_diet_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure_food_customer', models.IntegerField()),
                ('customer_food', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('food_field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='food.food')),
            ],
        ),
        migrations.CreateModel(
            name='food_diet_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesure_food_admin', models.IntegerField()),
                ('admin_food', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customer.customer')),
                ('food_field_admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='food.food')),
            ],
        ),
    ]
